name: Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    uses: trancecode/github-workflows/.github/workflows/go-analysis.yml@main
    with:
      system-packages: ''
      golangci-args: '--disable=staticcheck'
      staticcheck-checks: 'inherit'
      go-cache: false
      ignore-paths: '*.md LICENSE docs/**'
