name: Code Analysis

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'doc/**'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'doc/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    uses: trancecode/github-workflows/.github/workflows/go-analysis.yml@main
    with:
      system-packages: ''
      golangci-args: '--disable=staticcheck'
      staticcheck-checks: 'inherit'
