name: Go

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


permissions:
  contents: read

jobs:
  build:
    uses: trancecode/github-workflows/.github/workflows/go-build-test.yml@main
    with:
      system-packages: ''
      test-command: 'go test -v ./...'
