name: Race Detector

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  race:
    uses: trancecode/github-workflows/.github/workflows/go-race.yml@main
    with:
      system-packages: ''
      xvfb: false
